/workspaces/php-static-analysis-sample/src/EntryPoint.php:45:14:error - TaintedHtml: Detected tainted HTML (see https://psalm.dev/245)
/workspaces/php-static-analysis-sample/src/EntryPoint.php:45:14:error - TaintedTextWithQuotes: Detected tainted text with possible quotes (see https://psalm.dev/274)
/workspaces/php-static-analysis-sample/src/FileVulnerability.php:19:34:error - TaintedFile: Detected tainted file handling (see https://psalm.dev/255)
/workspaces/php-static-analysis-sample/src/FileVulnerability.php:29:27:error - TaintedFile: Detected tainted file handling (see https://psalm.dev/255)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:38:14:error - TaintedEval: Detected tainted code passed to eval or similar (see https://psalm.dev/252)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:48:30:error - TaintedShell: Detected tainted shell code (see https://psalm.dev/246)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:59:28:error - TaintedUnserialize: Detected tainted code passed to unserialize or similar (see https://psalm.dev/250)
/workspaces/php-static-analysis-sample/src/XssVulnerability.php:18:14:error - TaintedHtml: Detected tainted HTML (see https://psalm.dev/245)
/workspaces/php-static-analysis-sample/src/XssVulnerability.php:18:14:error - TaintedTextWithQuotes: Detected tainted text with possible quotes (see https://psalm.dev/274)
/workspaces/php-static-analysis-sample/src/XssVulnerability.php:36:14:error - TaintedHtml: Detected tainted HTML (see https://psalm.dev/245)
/workspaces/php-static-analysis-sample/src/XssVulnerability.php:36:14:error - TaintedTextWithQuotes: Detected tainted text with possible quotes (see https://psalm.dev/274)
