/workspaces/php-static-analysis-sample/src/DatabaseVulnerability.php:11:13:warning - MissingPropertyType: Property App\DatabaseVulnerability::$pdo does not have a declared type - consider mixed (see https://psalm.dev/045)
/workspaces/php-static-analysis-sample/src/DatabaseVulnerability.php:13:33:warning - MissingParamType: Parameter $pdo has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/DatabaseVulnerability.php:22:21:warning - MissingReturnType: Method App\DatabaseVulnerability::getUserById does not have a return type (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/DatabaseVulnerability.php:22:33:warning - MissingParamType: Parameter $id has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/DatabaseVulnerability.php:33:21:warning - MissingReturnType: Method App\DatabaseVulnerability::searchUsers does not have a return type (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/DatabaseVulnerability.php:33:33:warning - MissingParamType: Parameter $name has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/DatabaseVulnerability.php:44:21:warning - MissingReturnType: Method App\DatabaseVulnerability::deleteUser does not have a return type (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/DatabaseVulnerability.php:44:21:error - PossiblyUnusedMethod: Cannot find any calls to method App\DatabaseVulnerability::deleteUser (see https://psalm.dev/087)
/workspaces/php-static-analysis-sample/src/DatabaseVulnerability.php:44:32:warning - MissingParamType: Parameter $userId has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/DeadCodeVulnerability.php:9:7:error - UnusedClass: Class App\DeadCodeVulnerability is never used (see https://psalm.dev/075)
/workspaces/php-static-analysis-sample/src/DeadCodeVulnerability.php:15:21:warning - MissingReturnType: Method App\DeadCodeVulnerability::unreachableCode does not have a return type (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/DeadCodeVulnerability.php:15:37:warning - MissingParamType: Parameter $value has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/DeadCodeVulnerability.php:20:9:error - UnevaluatedCode: Expressions after return/throw/continue (see https://psalm.dev/084)
/workspaces/php-static-analysis-sample/src/DeadCodeVulnerability.php:21:9:error - UnevaluatedCode: Expressions after return/throw/continue (see https://psalm.dev/084)
/workspaces/php-static-analysis-sample/src/DeadCodeVulnerability.php:28:22:warning - MissingReturnType: Method App\DeadCodeVulnerability::unusedMethod does not have a return type, expecting 'This method is never called' (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/DeadCodeVulnerability.php:37:21:warning - MissingReturnType: Method App\DeadCodeVulnerability::unusedVariable does not have a return type, expecting 'This is used' (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/DeadCodeVulnerability.php:40:9:error - UnusedVariable: $unused is never referenced or the value is not used (see https://psalm.dev/077)
/workspaces/php-static-analysis-sample/src/DeadCodeVulnerability.php:49:21:warning - MissingReturnType: Method App\DeadCodeVulnerability::alwaysTrueCondition does not have a return type, expecting 'Always true'|'Never reached' (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/DeadCodeVulnerability.php:52:13:error - RedundantCondition: Type 10 for $x is always >= 5 (see https://psalm.dev/122)
/workspaces/php-static-analysis-sample/src/DeadCodeVulnerability.php:63:21:warning - MissingReturnType: Method App\DeadCodeVulnerability::infiniteLoop does not have a return type, expecting void (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/EntryPoint.php:12:7:error - UnusedClass: Class App\EntryPoint is never used (see https://psalm.dev/075)
/workspaces/php-static-analysis-sample/src/FileVulnerability.php:15:21:warning - MissingReturnType: Method App\FileVulnerability::readFile does not have a return type, expecting false|string (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/FileVulnerability.php:15:30:warning - MissingParamType: Parameter $filename has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/FileVulnerability.php:26:21:warning - MissingReturnType: Method App\FileVulnerability::saveFile does not have a return type, expecting void (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/FileVulnerability.php:26:30:warning - MissingParamType: Parameter $path has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/FileVulnerability.php:26:37:warning - MissingParamType: Parameter $content has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/FileVulnerability.php:36:21:warning - MissingReturnType: Method App\FileVulnerability::loadTemplate does not have a return type, expecting void (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/FileVulnerability.php:36:21:error - PossiblyUnusedMethod: Cannot find any calls to method App\FileVulnerability::loadTemplate (see https://psalm.dev/087)
/workspaces/php-static-analysis-sample/src/FileVulnerability.php:36:34:warning - MissingParamType: Parameter $templateName has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/FileVulnerability.php:39:9:warning - UnresolvableInclude: Cannot resolve the given expression to a file path (see https://psalm.dev/106)
/workspaces/php-static-analysis-sample/src/FileVulnerability.php:46:21:warning - MissingReturnType: Method App\FileVulnerability::handleUpload does not have a return type, expecting void (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/FileVulnerability.php:46:21:error - PossiblyUnusedMethod: Cannot find any calls to method App\FileVulnerability::handleUpload (see https://psalm.dev/087)
/workspaces/php-static-analysis-sample/src/FileVulnerability.php:46:34:warning - MissingParamType: Parameter $uploadedFile has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:15:21:warning - MissingReturnType: Method App\SecurityVulnerability::generateToken does not have a return type, expecting non-falsy-string (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:15:21:error - PossiblyUnusedMethod: Cannot find any calls to method App\SecurityVulnerability::generateToken (see https://psalm.dev/087)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:18:20:error - InvalidScalarArgument: Argument 1 of md5 expects string, but int provided (see https://psalm.dev/012)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:25:21:warning - MissingReturnType: Method App\SecurityVulnerability::hashPassword does not have a return type, expecting non-falsy-string (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:25:21:error - PossiblyUnusedMethod: Cannot find any calls to method App\SecurityVulnerability::hashPassword (see https://psalm.dev/087)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:25:34:warning - MissingParamType: Parameter $password has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:35:21:warning - MissingReturnType: Method App\SecurityVulnerability::executeCode does not have a return type, expecting void (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:35:33:warning - MissingParamType: Parameter $code has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:35:33:error - PossiblyUnusedParam: Param #1 is never referenced in this method (see https://psalm.dev/134)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:45:21:warning - MissingReturnType: Method App\SecurityVulnerability::pingHost does not have a return type, expecting false|null|string (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:45:30:warning - MissingParamType: Parameter $host has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:48:19:error - ForbiddenCode: Unsafe shell_exec (see https://psalm.dev/002)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:56:21:warning - MissingReturnType: Method App\SecurityVulnerability::loadData does not have a return type (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:56:30:warning - MissingParamType: Parameter $serializedData has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:66:21:warning - MissingReturnType: Method App\SecurityVulnerability::login does not have a return type, expecting void (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:66:21:error - PossiblyUnusedMethod: Cannot find any calls to method App\SecurityVulnerability::login (see https://psalm.dev/087)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:66:27:warning - MissingParamType: Parameter $username has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:66:38:warning - MissingParamType: Parameter $password has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/SecurityVulnerability.php:66:38:error - PossiblyUnusedParam: Param #2 is never referenced in this method (see https://psalm.dev/134)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:9:7:error - UnusedClass: Class App\TypeSafetyVulnerability is never used (see https://psalm.dev/075)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:15:21:warning - MissingReturnType: Method App\TypeSafetyVulnerability::useUndefinedVariable does not have a return type, expecting bool (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:18:13:error - UndefinedVariable: Cannot find referenced variable $result (see https://psalm.dev/024)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:28:21:warning - MissingReturnType: Method App\TypeSafetyVulnerability::getUserName does not have a return type (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:28:33:warning - MissingParamType: Parameter $user has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:38:21:warning - MissingReturnType: Method App\TypeSafetyVulnerability::getData does not have a return type, expecting 'string data'|123 (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:38:29:warning - MissingParamType: Parameter $flag has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:50:21:warning - MissingReturnType: Method App\TypeSafetyVulnerability::getConfigValue does not have a return type (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:50:36:warning - MissingParamType: Parameter $config has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:50:45:warning - MissingParamType: Parameter $key has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:60:21:warning - MissingReturnType: Method App\TypeSafetyVulnerability::calculateTotal does not have a return type (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:60:36:warning - MissingParamType: Parameter $price has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:60:44:warning - MissingParamType: Parameter $quantity has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:70:21:warning - MissingReturnType: Method App\TypeSafetyVulnerability::processOptionalData does not have a return type, expecting int<0, max> (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/TypeSafetyVulnerability.php:73:23:error - PossiblyNullArgument: Argument 1 of strlen cannot be null, possibly null value provided (see https://psalm.dev/078)
/workspaces/php-static-analysis-sample/src/XssVulnerability.php:15:21:warning - MissingReturnType: Method App\XssVulnerability::displayUserInput does not have a return type, expecting void (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/XssVulnerability.php:15:38:warning - MissingParamType: Parameter $userInput has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/XssVulnerability.php:25:21:warning - MissingReturnType: Method App\XssVulnerability::renderComment does not have a return type, expecting non-falsy-string (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/XssVulnerability.php:25:35:warning - MissingParamType: Parameter $comment has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/XssVulnerability.php:34:21:warning - MissingReturnType: Method App\XssVulnerability::showMessage does not have a return type, expecting void (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/XssVulnerability.php:34:33:warning - MissingParamType: Parameter $message has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/XssVulnerability.php:43:21:warning - MissingReturnType: Method App\XssVulnerability::createLink does not have a return type, expecting non-falsy-string (see https://psalm.dev/050)
/workspaces/php-static-analysis-sample/src/XssVulnerability.php:43:21:error - PossiblyUnusedMethod: Cannot find any calls to method App\XssVulnerability::createLink (see https://psalm.dev/087)
/workspaces/php-static-analysis-sample/src/XssVulnerability.php:43:32:warning - MissingParamType: Parameter $url has no provided type (see https://psalm.dev/154)
/workspaces/php-static-analysis-sample/src/XssVulnerability.php:43:38:warning - MissingParamType: Parameter $title has no provided type (see https://psalm.dev/154)
